name: Push Emacs Configuration
on:
  push:
    paths:
    - 'home/config/emacs/*'

jobs:
  copy-emacs-config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Push emacs directory
      uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'home/config/emacs/'
        destination-repository-name: 'emacs'
        user-email: 'flodobeutlin@mailbox.org'
        destination-github-username: 'flodobeutlin'
